### ISSUE TITLE
Envoy如何拿到客户端目标域名

### ISSUE THREAD

**Issue by alalag1** [cloudnativeto/sig-istio#8]
小白求问：
Istio官方`Bookinfo ` demo中客户端通过指定域名及端口的方式发送请求`http://ratings.default.svc.cluster.local:9080`，之后经过iptables redirect到Envoy，
请问Envoy这里是如何知道当前拦截到的这个流量的目标地址是`ratings.default.svc.cluster.local`的呢？

**Comment by zhaohuabing** [comment]
简而言之，是通过Gateway上绑定的VirtualService得知到该URL需要转发到集群内哪个服务上的。

**Comment by alalag1** [comment]
> 简而言之，是通过Gateway上绑定的VirtualService得知到该URL需要转发到集群内哪个服务上的。
> 如果想了解内部的原理，可以看一下我前段时间在社区的一个一个分享 https://www.bilibili.com/video/BV1Sf4y1e7mr

好的 感谢，我看一下视频学习一下
